---
title: "Default Panda Configuration"
experiment: 
year: 2024
user:
instrument: "i22"
detector_config:

detector_config:
  detectors: ["saxs", "waxs"]
  multiplier: [1, 1, 1, 1] #ie first detector can run 4x faster than second
  saxs:
    detector: "Pilatus2M_SAXS"
    pixels: 512
    rasters: 512
  waxs:
    detector: "Pilatus2M_WAXS"
    pixels: 512
    rasters: 1


profile-0:
  start_method: 0
  cycles: 1
  in_trigger: "IMMEDIATE"
  out_trigger: "TTLOUT1"
  multiplier: [1, 1, 1, 1] #ie first set of detectors run at the bas clock, and others run as 1/N the speed of the first

  group-0:
    frames: 1
    wait_time: 100
    wait_units: "ms"
    run_time: 100
    run_units: "ms"
    wait_pause: False
    run_pause: False
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [0, 0, 0, 0]