env:
  sources:
    - kind: dodal
      module: dodal.beamlines.i22
    - kind: planFunctions
      module: mx_bluesky.beamlines.i22.serial
  events:
    broadcast_status_events: False
api:
  port: 25565
stomp:
  host: i22-control.diamond.ac.uk
