---
title: "Panda Configure"
experiment: "cm37271-5"
year: 2025
user: "Dixey"
instrument: "i22"
detector_config:

detector_config:
  detectors: ["saxs", "waxs"]
  saxs:
    detector: "Rapid2D"
    pixels: 512
    rasters: 512
  waxs:
    detector: "HotWaxs"
    pixels: 512
    rasters: 1


profile-0:
  start_method: 0
  cycles: 3
  in_trigger: "BITA_0"
  out_trigger: "TTLOUT1"
  multiplier: [1, 2, 4, 8, 16] #ie first set of detectors run at the bas clock, and others run as 1/N the speed of the first


  group-0:
    frames: 1
    wait_time: 3
    wait_units: "ms"
    run_time: 3
    run_units: "ms"
    wait_pause: false
    run_pause: false
    wait_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]

  group-1:
    frames: 1
    wait_time: 0
    wait_units: "ms"
    run_time: 1
    run_units: "ms"
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 1, 0, 0, 0, 0, 0, 0]

  group-2:
    frames: 8
    wait_time: 0
    wait_units: "ms"
    run_time: 1
    run_units: "ms"
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]

  group-3:
    frames: 1
    wait_time: 0
    wait_units: "ms"
    run_time: 3
    run_units: "ms"
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
  
  group-5:
    frames: 1
    wait_time: 3
    wait_units: "ms"
    run_time: 0
    run_units: "ms"
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [0, 0, 0, 0, 0, 0, 0, 0]




profile-1:
  start_method: 0
  cycles: 1
  in_trigger: "POSC_LT"
  out_trigger: "TTLOUT2"
  multiplier: [1, 2, 4, 8, 16] #ie first set of detectors run at the bas clock, and others run as 1/N the speed of the first

  group-0:
    frames: 1
    wait_time: 100
    wait_units: "ms"
    run_time: 100
    run_units: "ms"
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]