---
title: Panda Configure
experiment: cm37271-5
year: 2025
user: Default
instrument: i22
profile-0:
  id: 0
  cycles: 3
  in_trigger: IMMEDIATE
  out_trigger: TTLOUT1
  multiplier: [1, 2, 4, 8]
  group-0:
    id: 0
    frames: 1
    wait_time: 3000
    wait_units: MS
    run_time: 3000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [1, 0, 0, 0]
    run_pulses: [1, 0, 0, 0]
  group-1:
    id: 1
    frames: 1
    wait_time: 1000
    wait_units: MS
    run_time: 1000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 0]
  group-2:
    id: 2
    frames: 8
    wait_time: 1000
    wait_units: MS
    run_time: 1000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0]
  group-3:
    id: 3
    frames: 1
    wait_time: 1000
    wait_units: MS
    run_time: 3000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0]
  group-4:
    id: 4
    frames: 1
    wait_time: 3000
    wait_units: MS
    run_time: 1000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [0, 0, 0, 0]
profile-1:
  id: 1
  cycles: 1
  in_trigger: IMMEDIATE
  out_trigger: TTLOUT2
  multiplier: [1, 2, 4, 8]
  group-0:
    id: 0
    frames: 1
    wait_time: 1
    wait_units: S
    run_time: 1
    run_units: S
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 1, 1]
profile-2:
  id: 2
  cycles: 1
  in_trigger: IMMEDIATE
  out_trigger: false
  multiplier: [1, 2, 4, 8]
  group-0:
    id: 0
    frames: 5
    wait_time: 0
    wait_units: MS
    run_time: 1
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 0]
  group-1:
    id: 1
    frames: 500
    wait_time: 0
    wait_units: MS
    run_time: 5
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 1]
  group-2:
    id: 2
    frames: 500
    wait_time: 0
    wait_units: MS
    run_time: 5
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 1]
