---
title: Panda Configure
experiment: cuisdcivun
year: 2025
user: Default
instrument: i22
profile-0:
  id: 0
  cycles: 3
  in_trigger: BITA_0
  out_trigger: TTLOUT1
  group-0:
    id: 0
    frames: 1
    wait_time: 3
    wait_units: ms
    run_time: 3
    run_units: ms
    wait_pause: false
    run_pause: false
    wait_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
  group-1:
    id: 1
    frames: 1
    wait_time: 0
    wait_units: ms
    run_time: 1
    run_units: ms
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 1, 0, 0, 0, 0, 0, 0]
  group-2:
    id: 2
    frames: 8
    wait_time: 0
    wait_units: ms
    run_time: 1
    run_units: ms
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
  group-3:
    id: 3
    frames: 1
    wait_time: 0
    wait_units: ms
    run_time: 3
    run_units: ms
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
  group-4:
    id: 4
    frames: 1
    wait_time: 3
    wait_units: ms
    run_time: 0
    run_units: ms
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
profile-1:
  id: 1
  cycles: 1
  in_trigger: POSC_LT
  out_trigger: TTLOUT2
  group-0:
    id: 0
    frames: 1
    wait_time: 100
    wait_units: ms
    run_time: 100
    run_units: ms
    wait_pause: false
    run_pause: false
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
