---
setup:
  title: "Panda Configure"
  experiment: "cm37271-5"
  year: 2024
  user: "Dixey"
  instrument: "i22"
  detector_config:

detector_config:
  detectors: ["saxs", "waxs"]
  frequency_multiplier: [4, 1] #ie first detector can run 4x faster than second
  saxs:
    detector: "Rapid2D"
    pixels: 512
    rasters: 512
  waxs:
    detector: "HotWaxs"
    pixels: 512
    rasters: 1


profile-1:
  cycles: 3
  in_trigger: "something"
  out_trigger: "somethingelse"

  group-1:
    frames: 1
    wait_time: 3
    wait_units: "msec"
    run_time: 3
    run_units: "msec"
    wait_pause: False
    run_pause: False
    wait_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]

  group-2:
    frames: 1
    wait_time: 0
    wait_units: "msec"
    run_time: 1
    run_units: "msec"
    wait_pause: False
    run_pause: False
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 1, 0, 0, 0, 0, 0, 0]

  group-3:
    frames: 8
    wait_time: 0
    wait_units: "msec"
    run_time: 1
    run_units: "msec"
    wait_pause: False
    run_pause: False
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]

  group-4:
    frames: 1
    wait_time: 0
    wait_units: "msec"
    run_time: 3
    run_units: "msec"
    wait_pause: False
    run_pause: False
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0, 0, 0, 0, 0]
  
  group-5:
    frames: 1
    wait_time: 3
    wait_units: "msec"
    run_time: 0
    run_units: "msec"
    wait_pause: False
    run_pause: False
    wait_pulses: [0, 0, 0, 0, 0, 0, 0, 0]
    run_pulses: [0, 0, 0, 0, 0, 0, 0, 0]