Experiment:
  Timing:
    Profile:
      - Profile: 1
        Cycles: 1
        Start-Method: 0:
        Ext-Inhibit: false
        Trigger:
          Debounce: NaN NaN NaN NaN NaN NaN NaN 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
          Threshold: NaN 0.0 0.0 0.0 0.0 0.0 0.0 NaN NaN NaN NaN NaN NaN NaN NaN 0.0
        OutputTrigger:
          Inversion: 192
          Drive: 0
        Frames:
          - 1,3,msec,3,msec,No Pause,No Pause,10000000,10000000
          - 1,0,msec,1,msec,No Pause,No Pause,00000000,11000000
          - 8,0,msec,1,msec,No Pause,No Pause,00000000,10000000
          - 1,0,msec,3,msec,No Pause,No Pause,00000000,10000000
          - 1,100,msec,0,msec,No Pause,No Pause,00000000,00000000
      - Profile: 2
        Cycles: 1
        Start-Method: 0:
        Ext-Inhibit: false
        Trigger:
          Debounce: NaN NaN NaN NaN NaN NaN NaN 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
          Threshold: NaN 0.0 0.0 0.0 0.0 0.0 0.0 NaN NaN NaN NaN NaN NaN NaN NaN 0.0
        OutputTrigger:
          Inversion: 192
          Drive: 0
        Frames: 33,5,msec,1000,msec,No Pause,No Pause,00100000,11111111
