---
title: Panda Configure
experiment: cm40643-2/bluesky
instrument: i22
detectors: [saxs, waxs]
profile-0:
  profile_id: 0
  cycles: 3
  seq_trigger: IMMEDIATE
  multiplier: [1, 2, 4, 8]
  total_frames: 12
  duration_per_cycle: 32.0
  duration: 0
  group-0:
    group_id: 0
    frames: 1
    wait_time: 3000
    wait_units: MS
    run_time: 3000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [1, 0, 0, 0]
    run_pulses: [1, 0, 0, 0]
    wait_time_s: 3.0
    run_time_s: 3.0
    group_duration: 6.0
  group-1:
    group_id: 1
    frames: 1
    wait_time: 1000
    wait_units: MS
    run_time: 1000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 0]
    wait_time_s: 1.0
    run_time_s: 1.0
    group_duration: 2.0
  group-2:
    group_id: 2
    frames: 8
    wait_time: 1000
    wait_units: MS
    run_time: 1000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0]
    wait_time_s: 1.0
    run_time_s: 1.0
    group_duration: 16.0
  group-3:
    group_id: 3
    frames: 1
    wait_time: 1000
    wait_units: MS
    run_time: 3000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 0, 0, 0]
    wait_time_s: 1.0
    run_time_s: 3.0
    group_duration: 4.0
  group-4:
    group_id: 4
    frames: 1
    wait_time: 3000
    wait_units: MS
    run_time: 1000
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [0, 0, 0, 0]
    wait_time_s: 3.0
    run_time_s: 1.0
    group_duration: 4.0
profile-1:
  profile_id: 1
  cycles: 1
  seq_trigger: IMMEDIATE
  multiplier: [1, 2, 4, 8]
  total_frames: 1
  duration_per_cycle: 2
  duration: 0
  group-0:
    group_id: 0
    frames: 1
    wait_time: 1
    wait_units: S
    run_time: 1
    run_units: S
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 1, 1]
    wait_time_s: 1
    run_time_s: 1
    group_duration: 2
profile-2:
  profile_id: 2
  cycles: 1
  seq_trigger: IMMEDIATE
  multiplier: [1, 1, 1, 1]
  total_frames: 100
  duration_per_cycle: 100
  duration: 0
  group-0:
    group_id: 0
    frames: 100
    wait_time: 0
    wait_units: S
    run_time: 1
    run_units: S
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 1, 1]
    wait_time_s: 0
    run_time_s: 1
    group_duration: 100
profile-3:
  profile_id: 3
  cycles: 1
  seq_trigger: TTL1IN
  multiplier: [1, 2, 4, 8]
  total_frames: 100
  duration_per_cycle: 100
  duration: 0
  group-0:
    group_id: 0
    frames: 100
    wait_time: 0
    wait_units: S
    run_time: 1
    run_units: S
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 1, 1]
    wait_time_s: 0
    run_time_s: 1
    group_duration: 100
profile-4:
  profile_id: 4
  cycles: 1
  seq_trigger: IMMEDIATE
  multiplier: [1, 2, 4, 8]
  total_frames: 1005
  duration_per_cycle: 5.005
  duration: 0
  group-0:
    group_id: 0
    frames: 5
    wait_time: 0
    wait_units: MS
    run_time: 1
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 0]
    wait_time_s: 0.0
    run_time_s: 0.001
    group_duration: 0.005
  group-1:
    group_id: 1
    frames: 500
    wait_time: 0
    wait_units: MS
    run_time: 5
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 1]
    wait_time_s: 0.0
    run_time_s: 0.005
    group_duration: 2.5
  group-2:
    group_id: 2
    frames: 500
    wait_time: 0
    wait_units: MS
    run_time: 5
    run_units: MS
    pause_trigger: IMMEDIATE
    wait_pulses: [0, 0, 0, 0]
    run_pulses: [1, 1, 0, 1]
    wait_time_s: 0.0
    run_time_s: 0.005
    group_duration: 2.5
